spring:
  application:
    name: keycloak-admin-client
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/Mini-Project
keycloak:
  auth-server-url: http://localhost:8080
  realm: Mini-Project
  clientId: Mini-Project
  clientSecret: U0aDOMj9zY9CVrT52mEaI86MNUTIPvq4

springdoc:
  api-docs:
    path: /keycloak-admin-client/v3/api-docs
  swagger-ui:
    path: /keycloak-admin-client/swagger-ui.html
    oauth:
      client-id: Mini-Project
      client-secret: U0aDOMj9zY9CVrT52mEaI86MNUTIPvq4